cutoff_len: 4096
dataset: cocktail_FPB-(Sentiment)
dataset_dir: cocktails/cocktail_FPB-(Sentiment)
ddp_timeout: 180000000
deepspeed: cache/ds_z2_offload_config.json
do_train: true
finetuning_type: full
flash_attn: fa2
fp16: true
gradient_accumulation_steps: 1
include_num_input_tokens_seen: true
learning_rate: 3.0e-06
logging_steps: 1
lr_scheduler_type: cosine
max_grad_norm: 1.0
max_samples: 1000000000
model_name_or_path: meta-llama/Meta-Llama-3.1-8B-Instruct
num_train_epochs: 3
optim: adamw_torch
output_dir: cocktails/cocktail_FPB-(Sentiment)
packing: true
per_device_train_batch_size: 8
plot_loss: true
preprocessing_num_workers: 24
report_to: none
resize_vocab: true
save_only_model: true
save_strategy: 'no'
save_total_limit: 1
stage: sft
template: llama3
